#!/usr/bin/env bash
set -o errexit

declare PLATFORM
PLATFORM="$(uname -s)"

declare -r ARCH="${PLATFORM,,}-amd64"
declare -r LICENCE="tools.hana.ondemand.com/developer-license-3_1.txt"


retrieve() {

  # Download tarball of latest version and extract the btp binary
  local filename="btp-cli-$ARCH-latest.tar.gz"

  curl \
      --fail \
      --silent \
      --location \
      --output "$filename" \
      --header "Cookie: eula_3_1_agreed=$LICENCE; path=/;" \
      "https://tools.hana.ondemand.com/additional/$filename" \
    && tar \
      --file "$filename" \
      --extract \
      --gunzip \
      --strip-components 1 \
      "$ARCH/btp" \
    && mv btp bin/btp

}

main() {
  retrieve  || {
    echo "Failed to find version"
    exit 1
  }

}

main "$@"
